### ISSUE TITLE
Variance of AliasableMut is incorrect

### ISSUE THREAD

**Issue by talchas** [avitex/rust-aliasable#3]
It uses `NonNull<T>` and `PhantomData<&'a ()>` which results in being covariant in `T`. A mutable pointer/reference must be invariant in `T`:

```rust
use aliasable::AliasableMut;
fn invalid<'a, 'b>(x: &'a mut &'static i32) -> &'a mut &'b i32 {
    AliasableMut::into_unique(AliasableMut::from_unique(x))
}

fn explode(x: &mut &'static i32) {
    let y = 2;
    *invalid(x) = &y;
}

fn main() {
    let mut x = &1;
    explode(&mut x);
    println!("{}", x);
}
```
prints 32767 on my machine.

**Comment by avitex** [comment]
Thanks, good find! Really should have picked this up.

**Comment by avitex** [comment]
This should be fixed in https://github.com/avitex/rust-aliasable/commit/4daf4bcb598116fd53cfeb00722dcd99d55fd303, but I want to just check a few more things before I push a release

**Comment by talchas** [comment]
Yeah, that should be correct.

**Comment by steffahn** [comment]
@avitex

Would you mind eventually releasing a version of this crate that includes this soundness fix?

**Comment by jayvdb** [comment]
ping @avitex , can you do a release?
